---
title: "ROMSNPZ_UW & ACLIM query updates"
author: "Kirstin Holsman"
date: "3/1/2018"
output:
  pdf_document:
    fig_caption: yes
    fig_height: 4
    fig_width: 5
    highlight: tango
    keep_tex: yes
    latex_engine: xelatex
  html_document:
    df_print: kable
    fig_caption: yes
    theme: flatly
  header-includes:
  - \usepackage{inputenc}
  - \usepackage{unicode-math}
  - \pagenumbering{gobble}
  word_document:
    fig_caption: yes
    fig_width: 4
    keep_md: yes
---

# Accessing ROMSNPZ on mox (hyak UW)
If you have a UW ID and are authorized on hyak (can do this through myUW.com, under settings>computing):

## 1) Accessing new Runs (UW):

### Login to Mox and make grid for 30 K
```{bash depths, include=FALSE}
 screen  # open new screen (ctrl A+D to exit; screen -r to return screen -ls to see list)
  ssh kkari@mox.hyak.uw.edu
  ## password : J bday + Josie’s dog (cap S on both) +!!  DEFUNCT holsman famnum +daughter (capJ)+!!
  ls /gscratch/bumblereem/bering10k/output/forecasts/cmip6
  # first check to see if things are running on bumblereem
  # You can always see reservations with the "scontrol show res" command.
  scontrol show hostnames
 
   srun -p bumblereem --time=72:00:00 --mem=20G --pty /bin/bash
  # record number here: 1579360
   cd /gscratch/bumblereem/holsman/ROMS_NPZ_scripts
   
  
  # Look for the R module via:  
    module available
  #Load it through:  
    module load r_3.3.3
    
    cd /gscratch/bumblereem/bering10k/output/forecasts/cmip6/ACLIM_ROMS_indices
    
     scp kkari@mox1:/gscratch/bumblereem/bering10k/output/forecasts/cmip6/ACLIM_ROMS_indices/ACLIMregion_B10K-H16_CMIP5_CESM_BIO_rcp85.nc /Users/kholsman/GitHub_new/ACLIM_romsnpz/Data/ACLIMregion_B10K-H16_CMIP5_CESM_BIO_rcp85.nc 
     
     
   scp kkari@mox1:/path/to/remote/file /path/to/local/file
  # view it with:
    ls  /gscratch/bumblereem/bering10k/output/hindcasts/bestnpz_aclim/Out

  # Look for the R module via:  
    module available
    
    #2461267 bumbleree     bash    kkari  R       1:36      1 n2217
            
```

## 3) FIRST TIME ONLY create lookup files for timesteps
```{preslurm, eval=FALSE}

R

  #  First time with a new model: create lookup files for timesteps
  #  setwd("/Users/kholsman/Documents/D_AFSC_Files/AFSC_code/07_ROMSNPZ_scripts_mox/")
  #  "/gscratch/bumblereem/holsman/ROMS_NPZ_scripts"
  
  updateTLOOKUP  <-  TRUE
  cntrl          <-  read.csv("aclim_qry_ControlFile.csv",header= T)
  qrypath        <-  "qry_lkups"
  if(!dir.exists(qrypath)) dir.create(qrypath)
   if(updateTLOOKUP) 
      source("get_TLOOKUP.R")
 
  dirlist        <-  dir(qrypath)[grep("K19",dir(qrypath))]
  fixit          <-  TRUE
  
  # now write to .csv files
  for(i in 1:length(dirlist)){
    load(file.path(qrypath,dirlist[i]))
    nm  <-  substring(dirlist[i],8,nchar(dirlist[i])-6)
    
    if(fixit) colnames(time_lookup) <- c("otime", "model", "tstep", "fname", "date" )
    subtab  <- data.frame(
        otime = time_lookup$otime,
        fname = time_lookup$fname,
        tstep = time_lookup$tstep,
        date  = time_lookup$date)
    write.table(x=subtab,
                sep=",",eol= "\r\n",row.names = FALSE,
                file=paste0("ROMS_NPZ_scripts/aclim_qry_lookup/Tlookup_files/",nm,"_lkup.csv"))
    rm(time_lookup)
  }
 
 q("no")
```



## 3) Run batch jobs on mox using slurm:
```{R, eval=FALSE}
 
screen  # open new screen (ctrl A+D to exit; screen -r to return screen -ls to see list)
source ~/.bash_profile

ssh kkari@mox.hyak.uw.edu
## password : J bday + Josie’s dog (cap S on both) +!!  DEFUNCT holsman famnum +daughter (capJ)+!!
 
cd /gscratch/bumblereem/holsman/ROMS_NPZ_scripts

# first check to see if things are running on bumblereem  
#You can always see reservations with the "scontrol show res" command.

# to view your jobs:
 squeue -u kkari
 
#To cancel:
# scancel -u kkari  
# scancel 1595389 
 
# Load node on bumblereem:
srun -p bumblereem --time=3:00:00 --mem=20G --pty /bin/bash
1595384

module load r_3.3.3

 # Submit a batch job from mox login node:
 

 # make_SurveyReplicated_Indices
 sbatch /gscratch/bumblereem/holsman/ROMS_NPZ_scripts/batch_slurm_files/ACLIM_SurveyReplicated.slurm
 
 # Runs make_Weekly_Indices.R
 sbatch /gscratch/bumblereem/holsman/ROMS_NPZ_scripts/batch_slurm_files/ACLIM_Weekly.slurm  

 # 
 sbatch /gscratch/bumblereem/holsman/ROMS_NPZ_scripts/batch_slurm_files/ACLIM_Weekly_crosshself.slurm

 # do this next 
 sbatch /gscratch/bumblereem/holsman/ROMS_NPZ_scripts/batch_slurm_files/ACLIM_gridded_weekly.slurm

            JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
           1612818 bumbleree   weekly    kkari  R       0:15      1 n2217
           1612817 bumbleree srvy_rep    kkari  R       0:20      1 n2215


#To see your jobs:
squeue -u kkari
# cancel the job: 
# scancel -u kkari  
# scancel 1579397  


#Detach from screen: ctl a + d  
#get list of screens: screen -ls
#reattach screen: screen -r [name]

# to get report on finished jobs
seff [job num]

#lapply(nc$dim, `[`, "units")
```

### Login to Mox and find hindcast:
```{bash, eval=FALSE}
            
            # now run R query:
            Rscript $"aclim_stationVals_master.R"
```








## 3a) BELOW HERE DEFUNCT


## 2) ONLY First time through:
### make TLOOKUP from .des file:

```{bash, eval=FALSE}
  
  #!/bin/sh
  cd /Users/kholsman/Documents/D_AFSC_Files/AFSC_code/ROMS_NPZ_scripts/aclim_qry_lookup
  grep 's_filename' aclim_hindcast_on_mox_v2.mc | cut -d\' -f2| grep -v 'END' > aclim_hindcast_on_mox_v2.txt
    
  ## If first time loading ncdf4 library in R on mox:
  R CMD INSTALL /gscratch/home/kkari/R/x86_64-pc-linux-gnu-library/3.3/ncdf4_1.16.tar.gz --configure-args="--with-nc-config=/gscratch/sw/netcdf-fortran+c-4.4.1.1_icc-17/bin/nc-config"
  
  # Use filezilla to transfer files and then navigate 
  # to the location on mox and open R and create lookup table:
  cd /gscratch/bumblereem/holsman/ROMS_NPZ_scripts
  module load r_3.3.3
  # now open R:
  R
    require(ncdf4,lib.loc="/gscratch/home/kkari/R/x86_64-pc-linux-gnu-library/3.3")
    
    makelook <- function(fname,outname){ 
       if (file.exists(outname)){
           print("remove file")
           file.remove(outname)
          #file.create(outname)
           # do nothing
       } else {
          #file.create(outname)
        
       }
       FL <- scan(fname,what="character") 
       otime <- NULL
       fname  <- NULL
       tstep <- NULL
       nf<-length(FL)
       i<-0
       for (f in FL){
          i<-i+1
          cat(round(100*(i/nf),1),"% complete ",f,"\n"); flush.console()
      	  nc <- nc_open(f)
      	  tt <- nc$dim$ocean_time$vals
      	  otime <- c(otime, tt)
      	  tstep <- c(tstep, seq(1,length(tt)))
          fname <- c(fname, rep(f,length(tt)))
      	  nc_close(nc)		
       } 
       write.csv(data.frame(otime,fname,tstep),outname,row.names=FALSE)
    }
    #makelook("GFDL_rcp85.txt","GFDL_rcp85.csv")
    makelook("aclim_qry_lookup/aclim_hindcast_on_mox_v2.txt","aclim_qry_lookup/aclim_hindcast_on_mox_v2.csv")
    
```



```{bash, eval=FALSE}
  
  # Login to Beast using:
  # host = sftp://afsc-s45.afsc.noaa.gov
  # Username= holsmanK
  # password = Droped$ruler4

```
## 3b) On MOX/HYAK:
```{bash, eval=FALSE}
https://wiki.cac.washington.edu/display/hyakusers/Mox_scheduler

    # USE this: Generic session for running jobs on the build nodes:
      srun -p build --time=12:00:00 --mem=10G --pty /bin/bash
      
    # Bumblereem session for running jobs on the reem nodes: 
      srun -p bumblereem --time=12:00:00 --mem=10G --pty /bin/bash

    # To get an interactive node in your own group for 2 hours:
      srun -p xyz -A xyz --time=10:00:00 --mem=100G --pty /bin/bash
      
    # To get an interactive node with 4 cores in your own group for 2 hours on mox:
      srun -p xyz -A xyz --nodes=1 --ntasks-per-node=4 --time=2:00:00 --mem=100G --pty /bin/bash

    # To get 2 nodes with 28 cores per node for interactive use:
       srun --nodes 2 --ntasks-per-node 28 -p xyz -A xyz  --time=2:00:00 --mem=100G --pty /bin/bash
    
    # Batch jobs:
      sbatch -p xyz -A xyz /gscratch/bumblereem/holsman/ROMS_NPZ_scripts/ACLIM_qry.slurm 
    
    # Use scancel to cancel jobs. For example to cancel a job with job id 1234:
      scancel 1234
      
    # If your userid is abc then you can cancel all your jobs by using below command:
     # scancel -u abc
       scancel -u kkari
    
  # where ACLIM_qry.slurm might be :
  #--------------------------------------------------- 
  
            #!/bin/bash
            ## Job Name
            #SBATCH --job-name=aclim_qry
            
            ## Allocation Definition 
            #SBATCH --account=xyz 
            #SBATCH --partition=xyz
            
            ## Resources
            ## Nodes
            #SBATCH --nodes=1   
            
            ## Walltime (3 hours)
            #SBATCH --time=72:00:00
            
            ## Memory per node
            #SBATCH --mem=10G
            
            ## Specify the working directory for this job
            #SBATCH --workdir=/gscratch/bumblereem/holsman/ROMS_NPZ_scripts
            
            ##turn on e-mail notification
            #SBATCH --mail-type=ALL
            #SBATCH --mail-user=kirstin.holsman@noaa.gov
            
            cd /gscratch/bumblereem/holsman/ROMS_NPZ_scripts
            module load r_3.3.3
            
            ## now run R query:
            Rscript $"aclim_stationVals_master.R"
            
  #---------------------------------------------------
```

## 4) Create ACLIM indices:
Now query the netcdf files for the indices and weekly station data (expand stations to include N bering, FOCI etc.). Confirm that the name of the TLookup files are the same as the corresponding colum in the aclim_qry_ControlFile.csv.

```{r makeIndices, eval=FALSE}

cd /gscratch/bumblereem/holsman/ROMS_NPZ_scripts

#To see your jobs:
squeue -u kkari

# Load node on bumblereem:
srun -p bumblereem --time=1:00:00 --mem=20G --pty /bin/bash
# job number: 1580305
# cancel the job: 
# scancel -u kkari  
# scancel 1579397  


#Submit a batch job from mox login node:

#sbatch myscript.slurm
 sbatch /gscratch/bumblereem/holsman/ROMS_NPZ_scripts/batch_slurm_files/ACLIM_SurveyReplicated.slurm
 sbatch -p xyz -A xyz /gscratch/bumblereem/holsman/ROMS_NPZ_scripts/batch_slurm_files/ACLIM_Weekly_crosshself.slurm
 sbatch -p xyz -A xyz /gscratch/bumblereem/holsman/ROMS_NPZ_scripts/batch_slurm_files/ACLIM_Weekly.slurm

#To see your jobs:
squeue -u kkari
# cancel the job: 
# scancel -u kkari  
# scancel 1579397  

# to get report on finished jobs
seff [job num]

cd /gscratch/bumblereem/holsman/ROMS_NPZ_scripts
module load r_3.3.3
 
# open R  
 R

#  First time with a new model: create lookup files for timesteps
if(updateTLOOKUP){
  qrypath<-"ROMS_NPZ_scripts/qry_lkups"
  source("get_TLOOKUP.R")
  dirlist  <- dir(qrypath)[grep("K19",dir(qrypath))]
  fixit <- TRUE
  # now write to .csv files
  for(i in 1:length(dirlist)){
    load(file.path(qrypath,dirlist[i]))
    nm  <-  substring(dirlist[i],8,nchar(dirlist[i])-6)
    
    if(fixit) colnames(time_lookup) <- c("otime", "model", "tstep", "fname", "date" )
    subtab  <- data.frame(time_lookup$otime,time_lookup$fname,time_lookup$tstep,time_lookup$date)
    write.table(x=subtab,
                sep=",",eol= "\r\n",row.names = FALSE,
                file=paste0("ROMS_NPZ_scripts/aclim_qry_lookup/Tlookup_files/",nm,"_lkup.csv"))
    rm(time_lookup)
  }
 
  
}
  

    #------------------------------------------------------------------------
    # model_num     model
    #------------------------------------------------------------------------
    	# 0             CORE_CFS_hindcast
    	# 1             MIROC_A1B
    	# 2             ECHOG_A1B
    	# 3             CCCMA_A1B
    	# 4             GFDL_rcp45
    	# 5             GFDL_rcp85
    	# 6             GFDL_rcp85_bio
    	# 7             MIROC_rcp45
    	# 8             MIROC_rcp85
    	# 9             CESM_rcp45
    	# 10            CESM_rcp85
    	# 11            CESM_rcp85_bio
    	# 12            aclim_hindcast
    	# 13            aclim_hindcast through 2018
      # 13            K19_hincast
    	# 14            OA_K19_GFDL_rcp45
    	# 15            OA_K19_GFDL_rcp85
    	# 16            OA_K19_MIROC_rcp45
    	# 17            OA_K19_MIROC_rcp85
    	# 18            OA_K19_CESM_rcp45
    	# 19            OA_K19_CESM_rcp85
    #------------------------------------------------------------------------
    # For Kirstin, and others looking for ROMS output data:
 
    # H16, 10-layer, CMIP3 forecasts (transferred from beast):
    # /gscratch/bumblereem/bering10k/output/cmip3-avg
 
    # H16, 10-layer, CMIP5 forecasts (transferred from beast):
    # /gscratch/bumblereem/bering10k/output/cmip5-avg
 
    # K19-P19, 30-layer, with carbon, CMIP5 forecasts (transferred from Darren): 
    # /gscratch/bumblereem/bering10k/output/cmip5-avg-carbon 
    
    # H16, 10-layer, hindcast (CORE/CFS hybrid):
    # /gscratch/bumblereem/bering10k/output/hindcasts/npz_201904_aclim
    
    # K19, 30-layer, hindcast (CORE/CFS hybrid):
    # /gscratch/bumblereem/bering10k/output/hindcasts/npz_201904_delta30


    		rm(list=ls())
      	# load packages
        	require(ncdf4,lib.loc="/gscratch/home/kkari/R/x86_64-pc-linux-gnu-library/3.3")
        #install.packages("fields",lib="/gscratch/home/kkari/R/x86_64-pc-linux-gnu-library/3.3")
        	require(fields,lib.loc="/gscratch/home/kkari/R/x86_64-pc-linux-gnu-library/3.3")
    
    	  # set root directory
        #root<-"/Users/kholsman/Documents/D_AFSC_Files/AFSC_code/ROMS_NPZ_scripts"
        	root<-"/gscratch/bumblereem/holsman/ROMS_NPZ_scripts"
        	setwd(root)
        	script_dir<-file.path(root)
        
      	# Load key functions
      		source(file.path(script_dir,"bering10K_func_clean.r"))
      		fl_lookup<-data.frame(read.csv(file.path(script_dir,"aclim_qry_ControlFile.csv")))
        
      	# now run the full query:
      	#	source(file.path(script_dir,"aclim_stationVals_master.R"))
      	
      ### OR RUN it by hand below:	
      		
    	# set up switches (DEFUNCT)
    # 		model_set         <-  0:12 # full set of models
    # 		ACLIM_set         <-  4:12
    # 		K19OA_test        <-  13:19
    # 		
    # 		plotit            <-  1    # make some plots? 1= yes
    # 		replace_files     <-  1    # replace existing output files?
    # 		update.statvals   <-  1 	# update the survey replicated values? 1= yes
    # 		update.weeklyvals <-  1  	# update the weekly values? 1= yes
    # 		update.cross_self <-  1  	# update the weekly values? 1= yes
    # 		update.subROMS    <-  0
    #     updateList        <-  model_set 	# update all
    #     
    #     updateList  <- 13  # ROMSNPZ_K19 hindcast (Kearney)
    #     updateList  <- 14:16  
    #     updateList  <- 17:19
       
        
      	#------------------------------------------------------------------------
        # Part1: Get station specific values based on mean sampling dates at each station
        #------------------------------------------------------------------------
    	    if(update.statvals==1) {
    	    	for(mmml in updateList){
    	  		    # set things up and make some plots:
    	  		    source(file.path(script_dir,"aclim_stationVals_Sub0.R"))
    	  		    source(file.path(script_dir,"aclim_stationVals_Sub1.R"))
    	  		    dir(paste("ROMSNPZ_outputs/",OUTFILE,sep=""))
    	    	}}	
        #------------------------------------------------------------------------
      	# Part2: Get weekly mean values for entire survey area
      	#------------------------------------------------------------------------
    	  	if(update.weeklyvals==1) {
    	  		for(mmml in updateList){
    	  		    # set things up and make some plots:
    	  		    source(file.path(script_dir,"aclim_stationVals_Sub0.R"))
    	  		    source(file.path(script_dir,"aclim_stationVals_Sub2.R"))
    	  			  dir(paste("ROMSNPZ_outputs/",OUTFILE,"/By_Station_csv",sep=""))
    	  	}}
      	#------------------------------------------------------------------------
        # Part3: Get weekly mean values for each cross shelf area
        #------------------------------------------------------------------------
    	  	if(update.cross_self==1){
    	  		for(mmml in updateList){
    	  		    # set things up and make some plots:
    	  		    source(file.path(script_dir,"aclim_stationVals_Sub0.R"))
    	  		    source(file.path(script_dir,"aclim_stationVals_Sub3.R"))
    	  	}}
      	#------------------------------------------------------------------------
      	# Part4: Get high res weekly values for a few values and a reduced grid from the whole EBS
      	#------------------------------------------------------------------------
    	  	if(update.subROMS==1) {
    	  		for(mmml in updateList){
    	  		    # set things up and make some plots:
    	  		    source(file.path(script_dir,"aclim_stationVals_Sub0.R")) 
    	  		    # higher res version, survey area  - weekly (715 K steps)
    	  		      subDat1<-highResWeekly[highResWeekly$full_survey==1,]; nss<-dim(subDat1)[1]
    	  		      nss*12*4*(2017-1970)
    	  		    # Lower res version, whole EBS - weekly (203 K steps)
    	  		      subDat2<-highResWeekly2[highResWeekly2$sub_ROMS2==1,]; nss2<-dim(subDat2)[1]
    	  		      nss2*12*4*(2017-1970)
    	  		    # High res version, whole EBS - monthly (335 K steps)  
      	  		    subDat3<-highResWeekly[highResWeekly$sub_ROMS2==1,]; nss3<-dim(subDat3)[1] 
      	  		    nss3*12*(2017-1970)
      	  		    subDat<-subDat2
      	  		    ns_sub<-dim(subDat)[1]
    	  		    # source(file.path(script_dir,"aclim_stationVals_Sub4.R"))
    	  	}}
    
    


```

# To install software:

If the software is not available then you will need to install it. You may be used to installing software on your desktop machine as root or administrator. However, it is not necessary to be root or administrator to install software on hyak. Almost all closed source software allows you to choose the installation path during the install process.


```{bash,eval=FALSE}
#Below we describe the steps for installing open source software. In below description xyz is your group name on hyak and abc is your userid on hyak. Below steps are for installing glpk. Modify the steps as appropriate for your software.
 
 ssh kkari@mox.hyak.uw.edu
## password : J bday + Josie’s dog (cap S on both) +!!  DEFUNCT holsman famnum +daughter (capJ)+!!
  cd /gscratch/bumblereem/holsman/admbstuff
  
srun -p build --time=2:00:00 --mem=10G --pty /bin/bash

#(Note:     (a) --pty /bin/bash must be the last option in above command.
#           (b) If you do not get a build node with above values of --mem, then try smaller values.)
 mkdir admbstuff
 cd admbstuff

#http://www.admb-project.org/downloads/admb-12.0/QuickStartUnixSource.html
srun -p build --time=2:00:00 --mem=10G --pty /bin/bash
wget https://github.com/admb-project/admb/releases/download/admb-12.0/admb-12.0-src.zip
unzip admb-12.0-src.zip
cd admb
make

# now test that the install worked:
cd examples/admb/simple
/gscratch/bumblereem/holsman/admbstuff/admb/admb simple.tpl  # or ~/admb/admb.sh simple.tpl
./simple


./configure --prefix=/gscratch/xyz/abc/myinstalldir/glpk-4.54install
make
make install
At this stage the software is installed in the directory give by the --prefix option. Look inside the directory for the bin directory and put the complete path to the bin directory in you PATH variable in your .bashrc like below:
export PATH=/gscratch/xyz/abc/myinstalldir/glpk-4.54install/bin:$PATH
Logout and login and issue the command for your newly installed software.
*Note: *
The above description is for the basic steps. If you want more options for installing and compiling the software then use below command to find the possible choices:
./configure -help ( or -h or --help) gives details about options)

```


```{bash, eval=FALSE}



# 

filename = '/Users/kholsman/GitHub/CEATTLE/src/ceattle-master/main/dat_input_files/01_assessment_2019/stomach2019.dat'

echo $filename

 ssh kkari@mox.hyak.uw.edu
 sftp kkari@mox.hyak.uw.edu
 cd /gscratch/bumblereem/holsman
 
put /Users/kholsman/GitHub/CEATTLE.zip
 
 get stomach2019.dat
 
 quit
 
 srun -p build --time=2:00:00 --mem=10G --pty /bin/bash
 mkdir ceattle

#Into Hyak via scp, e.g. command line:
scp ~/Users/kholsman/GitHub/CEATTLE/src/ceattle-master/main/dat_input_files/01_assessment_2019/stomach2019.dat  kkari@mox.hyak.uw.edu:/gscratch/bumblereem/holsman/admbstuff



#Out of Hyak via scp, to local working directory
scp user@hyak.washington.edu:path/to/file .


```

## Create ROMSNPZ station lookup from lat lon data
# Ecofoci locations
# N EBS locations
# M2 moorings

---
# From Ivonne:
groupname: bumblereem  (hyak.bumblereem but no need to write hyak)

you'll need to install DUO app in a phone or tablet for authentication when you login in:
https://itconnect.uw.edu/security/uw-netids/2fa/

To connect open an ssh session and type:
`ssh youruwid@mox.hyak.uw.edu`

Your password is your UW e-mail password

When prompted to select DUO athetication select number 1  (1 being DUO push and you accept on your phone) or you can select options 2, 3 -type in code or get phone call.

You should see something like 

`ivonne@mox1 ~}$`   (or `ivonne@mox2`)

To see your groups type (not all groups are for node allocation):
`groups <youruwid>`

To see allocated nodes by group in mox (your node group should be there):
`hyakalloc`

You should have at least 2 groups:
`hyak-hpc` (12 nodes, 336 cores, 2976G) these nodes are for evaluation and are open to ANYONE on Mox

To see the various partitions (aka allocations):
`sinfo`
To see the usage of your group's nodes:
`squeue -p xyz`
Below mox specific command  shows  the number of nodes etc. of all allocations.
`hyakalloc`

`lolo-hyak` long term archival (slow retrieval, currently full)

Our shared scratch folder: `gscratch/bumblereem/`

Mox basics:  http://wiki.cac.washington.edu/display/hyakusers/Hyak_mox_HOWTO

Hyak/HPC basics:  http://wiki.cac.washington.edu/display/hyakusers/WIKI+for+Hyak+users

You can also go here:
https://github.com/sr320/LabDocs/wiki/Hyak-(MOX)-Computing

Instead of putty I now mostly use MobaXterm freeware which is a combo of putty-like ssh (and imports all your session settings) with graphics included (so you don't need XMing or similar) with full file access a la Filezilla and a text editor included, plus a bunch other goodies.

http://mobaxterm.mobatek.net/




